on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@HEAD
    - run: |
        gh release create --draft -- "$tag_name"
        gh release upload --clobber -- "$tag_name" /etc/os-release
        gh api -X PATCH "/repos/$GITHUB_REPOSITORY/git/refs/tags/$tag_name" -F force=true -f "sha=$GITHUB_SHA"
      env:
        GH_TOKEN: ${{github.token}}
        tag_name: ${{github.ref_name}}-nightly
