on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@HEAD
    - run: |
        gh release create --prerelease -- "$tag" || :
        gh release upload --clobber -- "$tag" /etc/os-release
        gh api -X PATCH "/repos/{owner}/{repo}/git/refs/tags/$tag" -F force=true -f "sha=$(git rev-parse @)"
      env:
        GH_TOKEN: ${{github.token}}
        tag: ${{github.ref_name}}-nightly
